### ISSUE TITLE
Snapshots to visualize partial state graphs

### ISSUE THREAD

**Issue by lemmy** [afonsonf/tlaplus-graph-explorer#1]
Nice work!

Note that TLC's dump flag has recently been extended with a `snapshot` sub-command, which will make TLC write the partial state graph after each new state ([example](https://github.com/lemmy/BlockingQueue#v03-state-graph-for-configurations-p1c2b1-and-p2c1b1)).  Combined with `TLCExt!PickSuccessor`, your explorer could run online.

**Comment by afonsonf** [comment]
Thank you!

I tried the snapshot sub-command, as shown in your example, and I think it would be interesting to add it.
An idea of how I would implement it would be to add a refresh button that would re parse the dot file. However, because this is in javascript and because the way I am reading the file, it would require to re select the file every time you refreshed. 

I will research what is the best way to implement it and add it in the next few days.

Thank you very much for your time and for sharing the project!
